import Head from 'next/head';
import { useContext } from 'react';
import Feed from '../components/Feed';
import Header from '../components/Header';
import Modal from '../components/Modal';
import { modalContext } from '../modalContext/modalContext';

export default function Home() {
	const openModal = useContext(modalContext);

	return (
		<div className='bg-gray-50 h-full'>
			<Head>
				<title>Instagram-clone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />

			<Feed />
			<div>{openModal && <Modal />}</div>
		</div>
	);
}
